# Generated by Django 5.1.3 on 2024-11-20 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='QnaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna', to='api.notesmodel', to_field='title')),
            ],
        ),
    ]
