# Generated by Django 5.1.3 on 2024-11-20 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_notesmodel_title_qnamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qnamodel',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna', to='api.notesmodel'),
        ),
    ]
